version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sqlserver
    networks:
      eclinic:
        ipv4_address: 172.20.0.1
    ports:
     - "1444:1433"
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Eclinic123
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    networks:
      eclinic:
        ipv4_address: 172.20.0.2
    ports:
     - "27018:27017"
  redis:
    image: "redis:latest"
    container_name: redis
    networks:
      eclinic:
        ipv4_address: 172.20.0.3
    ports:
     - "6379:6379"
  rabbitmq:
    image: "rabbitmq:3.11-management"
    container_name: rabbitmq
    networks:
      eclinic:
        ipv4_address: 172.20.0.4
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=eclinic
      - RABBITMQ_DEFAULT_PASS=eclinic
  project.identityservice:
    image: ${DOCKER_REGISTRY-}projectidentityservice
    build:
      context: .
      dockerfile: Project.IdentityService/Dockerfile
    networks:
      eclinic:
        ipv4_address: 172.20.0.5
  project.apigateways:
    image: ${DOCKER_REGISTRY-}projectapigateways
    build:
      context: .
      dockerfile: Project.APIGateways/Dockerfile
    networks:
      - eclinic
  project.profileservice:
    image: ${DOCKER_REGISTRY-}projectprofileservice
    build:
      context: .
      dockerfile: Project.ProfileService/Dockerfile
    networks:
      eclinic:
        ipv4_address: 172.20.0.6

  project.forumservice:
    image: ${DOCKER_REGISTRY-}projectforumservice
    build:
      context: .
      dockerfile: Project.ForumService/Dockerfile

  project.notificationservice:
    image: ${DOCKER_REGISTRY-}projectnotificationservice
    build:
      context: .
      dockerfile: Project.NotificationService/Dockerfile

  project.testservice:
    image: ${DOCKER_REGISTRY-}projecttestservice
    build:
      context: .
      dockerfile: Project.TestService/Dockerfile

networks:
  eclinic:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24




