// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.CommunicateService.Data.Configurations;

#nullable disable

namespace Project.CommunicateService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230726132650_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Project.CommunicateService.Data.ChatMessage", b =>
                {
                    b.Property<Guid>("ChatMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoomID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatMessageID");

                    b.HasIndex("RoomID");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("Project.CommunicateService.Data.Room", b =>
                {
                    b.Property<Guid>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReceiverID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomID");

                    b.HasIndex("RoomTypeID");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Project.CommunicateService.Data.RoomType", b =>
                {
                    b.Property<Guid>("RoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("RoomTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomTypeID");

                    b.ToTable("RoomTypes", (string)null);

                    b.HasData(
                        new
                        {
                            RoomTypeID = new Guid("bde8645f-2760-4729-ac4f-1c5b5ffedc2a"),
                            RoomTypeName = "Doctor"
                        },
                        new
                        {
                            RoomTypeID = new Guid("0ddb55c3-b551-4e04-b827-07ea8d777130"),
                            RoomTypeName = "Supporter"
                        });
                });

            modelBuilder.Entity("Project.CommunicateService.Data.ChatMessage", b =>
                {
                    b.HasOne("Project.CommunicateService.Data.Room", "Room")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PK_ChatRoom_Many_To_One_ChatMessage");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Project.CommunicateService.Data.Room", b =>
                {
                    b.HasOne("Project.CommunicateService.Data.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PK_RoomType_Many_To_One_Room");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Project.CommunicateService.Data.Room", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("Project.CommunicateService.Data.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
