call IdentityService.bat
call ProfileService.bat
call ForumService.bat
call CommunicateService.bat
call ServiceInformationService.bat
call PaymentService.bat
call BookingService.bat
call BlogService.bat
call AIService.bat